apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-03-16T09:11:49Z"
  generateName: hosttailer-host-tailer-
  labels:
    app.kubernetes.io/instance: hosttailer-host-tailer
    app.kubernetes.io/name: host-tailer
    controller-revision-hash: 7f6fffdcc6
    pod-template-generation: "1"
  name: hosttailer-host-tailer-nqfgh
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: hosttailer-host-tailer
    uid: cd9de6bd-397e-4925-94f2-77c889d13248
  resourceVersion: "166114"
  uid: 4d557795-ac71-41a0-acce-ad70131e338f
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - kind-control-plane
  containers:
  - command:
    - /fluent-bit/bin/fluent-bit
    - -i
    - tail
    - -p
    - path=/shifter/date
    - -p
    - db=/var/pos/hosttailer-host-tailer-sample-date.db
    - -p
    - buffer_max_size=32k
    - -p
    - skip_long_lines=On
    - -o
    - file
    - -p
    - format=template
    - -p
    - template={log}
    - -p
    - path=/dev/
    - -p
    - file=stdout
    image: fluent/fluent-bit:1.6.1
    imagePullPolicy: IfNotPresent
    name: sample-date
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/pos
      name: positions
    - mountPath: /shifter
      name: shifter
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-xcp67
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: kind-control-plane
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  volumes:
  - hostPath:
      path: /var/pos
      type: ""
    name: positions
  - hostPath:
      path: /shifter
      type: ""
    name: shifter
  - name: kube-api-access-xcp67
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-03-16T09:11:49Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-03-16T09:12:32Z"
    message: 'containers with unready status: [sample-date]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-03-16T09:12:32Z"
    message: 'containers with unready status: [sample-date]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-03-16T09:11:49Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://7ba961b052f8283e9e586537dfec216a0715b7b5570e33d7d65c9a891107e199
    image: docker.io/fluent/fluent-bit:1.6.1
    imageID: docker.io/fluent/fluent-bit@sha256:9287fc70842bfa490bc5e7ccaf78a2fd1db6348afa7e1fd360035238090969fd
    lastState:
      terminated:
        containerID: containerd://7ba961b052f8283e9e586537dfec216a0715b7b5570e33d7d65c9a891107e199
        exitCode: 255
        finishedAt: "2022-03-16T09:17:28Z"
        reason: Error
        startedAt: "2022-03-16T09:17:28Z"
    name: sample-date
    ready: false
    restartCount: 6
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=sample-date pod=hosttailer-host-tailer-nqfgh_default(4d557795-ac71-41a0-acce-ad70131e338f)
        reason: CrashLoopBackOff
  hostIP: 172.18.0.2
  phase: Running
  podIP: 10.244.0.69
  podIPs:
  - ip: 10.244.0.69
  qosClass: BestEffort
  startTime: "2022-03-16T09:11:49Z"
