env:
  - name: ENABLE_WEBHOOKS
    value: "true"
volumes:
  - name: webhook-tls
    secret:
      secretName: webhook-tls
volumeMounts:
  - name: webhook-tls
    mountPath: /tmp/k8s-webhook-server/serving-certs